export type GENERAL_ITEM_TYPE = 'EMPTY' | 'COBRA' | 'CROCODILE' | 'ELAND' | 'GIRAFFE' | 'LEOPARD' | 'RHINO' | 'ZEBRA';
export type SPECIAL_ITEM_TYPE = 'ELEPHANT' | 'LION' | 'BUFFALO';
export type ITEM_TYPE = GENERAL_ITEM_TYPE | SPECIAL_ITEM_TYPE;

export const GENERAL_ITEM = {
  EMPTY: 'EMPTY' as GENERAL_ITEM_TYPE,
  COBRA: 'COBRA' as GENERAL_ITEM_TYPE,
  CROCODILE: 'CROCODILE' as GENERAL_ITEM_TYPE,
  // ELAND: 'ELAND' as GENERAL_ITEM_TYPE,
  // GIRAFFE: 'GIRAFFE' as GENERAL_ITEM_TYPE,
  LEOPARD: 'LEOPARD' as GENERAL_ITEM_TYPE,
  RHINO: 'RHINO' as GENERAL_ITEM_TYPE,
  ZEBRA: 'ZEBRA' as GENERAL_ITEM_TYPE,
}

export const SPECIAL_ITEM = {
  ELEPHANT: 'ELEPHANT' as SPECIAL_ITEM_TYPE,
  LION: 'LION' as SPECIAL_ITEM_TYPE,
  BUFFALO: 'BUFFALO' as SPECIAL_ITEM_TYPE,
}

export const EVENT = {
  GAME_LEVEL: 'GAME_LEVEL',
  GAME_SCORE: 'GAME_SCORE',
  GAME_SCORE_TARGET: 'GAME_SCORE_TARGET',
  GAME_MOVE: 'GAME_MOVE',
  GAME_MOVE_LIMIT: 'GAME_MOVE_LIMIT',
  GAME_LEVEL_SUCCESS: 'GAME_LEVEL_SUCCESS',
  GAME_LEVEL_FAILURE: 'GAME_LEVEL_FAILURE',
  GAME_RESTART: 'GAME_RESTART',
}
